### ISSUE TITLE
Unsupported command?

### ISSUE THREAD

**Issue by Plankton555** [Qthulu/shrdlite-course-project#22]
I looked through the example utterances in the html GUI and tested "put the brick that is to the right of a pyramid in a box" (original was using "left of", but I changed that). I get "Interpretation error: Found no legal interpretation", but from what I can see, there is legal interpretations. See picture.

![capture](https://cloud.githubusercontent.com/assets/1454000/7796680/0f00ed3c-02e2-11e5-8b16-15969ffcdfed.PNG)

**Comment by Plankton555** [comment]
Is there something in the command that is not supported, or is there a bug in the program?

**Comment by HalfLeif** [comment]
Put (the brick that is right of a pyramid) in (a box). The program correctly states that there is no such brick. Perhaps you were thinking of the "plank" or the "table"?

**Comment by Plankton555** [comment]
Looking at the picture, I can see two pyramids in a stack. To the right of them there are two bricks in another stack. So, yes, there are bricks to the right of a pyramid, and so there is such an interpretation. Or am I missing something?

**Comment by Plankton555** [comment]
Of course, one of the bricks that are to the right of a pyramid is already in a box, but then it should state that the plan had 0 steps and not throw an interpretation error. If anything, it should state that the command is ambiguous since there are two bricks.

**Comment by HalfLeif** [comment]
When we use "to the right of" we really mean "in the stack adjacent to the right of"

So there is no brick directly in the stack to the right of the pyramids

**Comment by HalfLeif** [comment]
Or at least, that is how I programmed it and as far as I can recall, what we agreed upon

**Comment by Plankton555** [comment]
Ah. The leftof/rightof used by the move commands (e.g. "put the box left of the pyramid") actually does not require the objects to be adjacent to each other. I thought it used the same interpretation regarding "to the right of", that's why I didn't understand it.

Maybe we should be consistent? It should be rather easy to change the move commands to also require adjacency if you want me to change it?

**Comment by HalfLeif** [comment]
Just leave it as it is please. The Interpreter and the Heuristics are designed for that. Frankly, I'm not sure what you mean. If there is something you think needs fixing, would mind calling me on Skype?

**Comment by HalfLeif** [comment]
In the small world, if you type
move the large ball to the left of the yellow box

the program correctly moves it to the adjacent stack left of the yellow box even though it's starting stack is to the far left of it. I think this behaviour is exactly what we want?

**Comment by Plankton555** [comment]
Hmm... what I meant has apparantly been changed, probably during some refactorisation or bugfix or something. When I implemented it, it just checked whether object1 was somewhere to the left of object2, but not anymore. Now they must be adjacent.

Closing this then, since everything is as it should.

**Comment by HalfLeif** [comment]
Yes, I "fixed" that previously. Interesting how different interpretations still exist in the group so late in a project that has been going on for quite a while
